server {
 listen 8080;
 server_name _;
 root /usr/share/nginx/html;
 location / { try_files $uri $uri/ /index.html; }
 location /api/ {
  client_max_body_size 6m;
  proxy_pass http://backend:8019;
  proxy_set_header Host $host;
 }
}
